49 populate the category page
MEDLY-FED22G/NetMovie pull request #54
Opened 2023-12-07 19:36 UTC by ye-mou

More styling might be needed but it does filter by category

2023-12-07 22:55 UTC, MimPMC requested changes
Vi behöver mappa över kategorierna i varje film, så det endast blir , Drama, Action, Horror, etc. separat och filmerna visas i varje separat kategori, istället för att ha kategorikombinationerna. Ex ska inte  "Drama,Horror,Romance" vara en separat kategori, utan filmen ska visas i både drama, horror och romance.

2023-12-08 14:53 UTC, Lvl1Pichu requested changes
Ser jättebra ut Yehad!

Ett par ändringar bara:

- De enda kategorierna som renderas ut just nu är: Action, Drama, Thriller. Vi skulle behöva att varje kategori som är unik renderas ut och kan klickas på

- När man navigerar till Category page är "Action" automatiskt ifylld

- Lägg gärna till ett gap av 2-4 mellan korten så det syns vart varje movie-card börjar och slutar

- Selected Category är en ostylad p-tag som inte ser ut att passa in på sidan, jag tänker att vi kan ta bort den helt då den category som vi markerar redan är ifylld! 

- Ska vi kunna klicka i flera categories? Eller ska en i taget räcka? Värt att diskutera på Måndag :)

2023-12-10 10:30 UTC, Emil-Helge approved these changes
Det ser ut att fungera som efterfrågat i föregående kommentarer och du har även fått med ytterligare ändringar som @Lvl1Pichu bad om(bl.a  att ingen kategori är automatiskt vald & gap mellan korten)

Jag avvaktar däremot med att merge:a tills vi har diskuterat  @Lvl1Pichu sistnämnda förslag("Ska vi kunna klicka i flera categories? Eller ska en i taget räcka?")

Bra jobbat!

2023-12-10 12:10 UTC, ye-mou commented
> Det ser ut att fungera som efterfrågat i föregående kommentarer och du har även fått med ytterligare ändringar som @Lvl1Pichu bad om(bl.a att ingen kategori är automatiskt vald & gap mellan korten)
> 
> Jag avvaktar däremot med att merge:a tills vi har diskuterat @Lvl1Pichu sistnämnda förslag("Ska vi kunna klicka i flera categories? Eller ska en i taget räcka?")
> 
> Bra jobbat!

Tack. Ja det låter som en bra plan.

2023-12-11 10:30 UTC, Lvl1Pichu approved these changes

2023-12-11 11:11 UTC, MimPMC approved these changes

2023-12-11 11:12 UTC, merged